#!/bin/sh


# Configure Traditional Chinese LuCI and the Taipei timezone on first boot.
uci -q set luci.main.lang='zh_tw'
uci -q set luci.main.mediaurlbase='/luci-static/argon'
uci -q set system.@system[0].hostname='AirPi-H5000M'
uci -q set system.@system[0].zonename='Asia/Taipei'
uci -q set system.@system[0].timezone='CST-8'


# Set custom LAN IP
uci -q set network.lan.ipaddr='192.168.1.1'
uci -q commit network


# Apply the requested US wireless regulatory domain to existing radios.
for radio in radio0 radio1; do
	if uci -q get "wireless.${radio}" >/dev/null; then
		uci -q set "wireless.${radio}.country=US"
	fi
done


# Force overwrite /etc/config/argon to ensure exactly ONE section exists.
cat << 'EOF' > /etc/config/argon
config global
	option mode 'dark'
	option primary '#0F766E'
	option main_primary '#0F766E'
	option dark_primary '#0F766E'
	option blur '10'
	option blur_dark '10'
	option transparency '0.5'
	option transparency_dark '0.5'
	option bing '1'
EOF


uci -q commit luci
uci -q commit system
